# scripts/check_processed_data.py
# -*- coding: utf-8 -*-
"""
Data quality check tool.

Traverse all CSV files generated by 'preprocess_clinical.py',
and check if there are any NaN (Not a Number / missing values).
"""
import pandas as pd
from pathlib import Path


def check_data_quality():
    """Main check function"""
    print("--- Starting comprehensive check of all processed data files ---")

    data_dir = Path("data/processed_clinical")

    if not data_dir.exists():
        print(f"❌ Error: Directory '{data_dir}' not found.")
        print("Please make sure you have successfully run the preprocessing script.")
        return

    # Find all processed fold CSV files
    csv_files = sorted(list(data_dir.glob("fold_*_*.csv")))

    if not csv_files:
        print(f"⚠️ Warning: No 'fold_*_*.csv' files found in {data_dir}.")
        return

    found_issue = False
    for file_path in csv_files:
        print(f"🔍 Checking file: {file_path.name}")
        try:
            df = pd.read_csv(file_path)

            # Check if the entire DataFrame has any NaN values
            if df.isnull().values.any():
                print(f"  ‼️‼️‼️ Warning: NaN (missing) values found in file '{file_path.name}'! ‼️‼️‼️")
                # Print which columns have how many NaN values
                nan_info = df.isnull().sum()
                print("  Missing value statistics:")
                print(nan_info[nan_info > 0])
                print("-" * 20)
                found_issue = True

        except Exception as e:
            print(f"  ❌ Error reading or checking file '{file_path.name}': {e}")
            found_issue = True

    if not found_issue:
        print("\n--- ✅ All files checked, no obvious NaN issues found. ---")
    else:
        print(
            "\n--- ❗ Issues found during check, please review the warnings above. Problems may originate from preprocessing script's filling logic not handling certain special cases. ---"
        )


if __name__ == "__main__":
    check_data_quality()
