name: DICOM to NIfTI Converter

on:
  push:
    branches: [ "codex/整理仓库为毕业论文结构" ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    name: Convert DICOM to NIfTI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DICOM to NIfTI conversion
        run: |
          mkdir -p nifti_output
          python scripts/dicom_to_nifti.py dicom_input nifti_output

      - name: Upload NIfTI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nifti-output
          path: nifti_output/
